builds:
  - dir: .
    goos:
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.name={{.ProjectName}} -X main.target={{.Os}}-{{.Arch}} -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: "{{.ProjectName}}"

archives:
  - name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^(?i)(t)ypo"
      - "^(?i)(m)erge"
  groups:
    - title: "Dependencies"
      regexp: '^.*?(feat|fix|sec|ref|test|docs|build)\(deps\)!?:.+$'
      order: 800
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 100
    - title: "Issues"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Security"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 300
    - title: "Refactor"
      regexp: '^.*?ref(\([[:word:]]+\))??!?:.+$'
      order: 400
    - title: "Test"
      regexp: '^.*?test(\([[:word:]]+\))??!?:.+$'
      order: 500
    - title: "Documentation"
      regexp: ^.*?docs(\([[:word:]]+\))??!?:.+$
      order: 600
    - title: "Build"
      regexp: ^.*?build(\([[:word:]]+\))??!?:.+$
      order: 700
    - title: "Other"
      order: 900
